#!/home/philippe/src/anomaly/venv/bin/python3
# coding: utf-8

import numpy as np

csv_dtypes = {
    'Flow ID': np.object,
    'Src IP': np.object,
    'Src Port': np.int16,
    'Dst IP': np.object,
    'Dst Port': np.int16,
    'Protocol': np.int8,
    'Timestamp': np.object,
    'Flow Duration': np.int64,
    'Tot Fwd Pkts': np.int64,
    'Tot Bwd Pkts': np.int64,
    'TotLen Fwd Pkts': np.int64,
    'TotLen Bwd Pkts': np.int64,
    'Fwd Pkt Len Max': np.int64,
    'Fwd Pkt Len Min': np.int64,
    'Fwd Pkt Len Mean': np.float64,
    'Fwd Pkt Len Std': np.float64,
    'Bwd Pkt Len Max': np.int64,
    'Bwd Pkt Len Min': np.int64,
    'Bwd Pkt Len Mean': np.float64,
    'Bwd Pkt Len Std': np.float64,
    'Flow Byts/s': np.float64,
    'Flow Pkts/s': np.float64,
    'Flow IAT Mean': np.float64,
    'Flow IAT Std': np.float64,
    'Flow IAT Max': np.float64,
    'Flow IAT Min': np.float64,
    'Fwd IAT Tot': np.float64,
    'Fwd IAT Mean': np.float64,
    'Fwd IAT Std': np.float64,
    'Fwd IAT Max': np.float64,
    'Fwd IAT Min': np.float64,
    'Bwd IAT Tot': np.float64,
    'Bwd IAT Mean': np.float64,
    'Bwd IAT Std': np.float64,
    'Bwd IAT Max': np.float64,
    'Bwd IAT Min': np.float64,
    'Fwd PSH Flags': np.int32,
    'Bwd PSH Flags': np.int32,
    'Fwd URG Flags': np.int32,
    'Bwd URG Flags': np.int32,
    'Fwd Header Len': np.int32,
    'Bwd Header Len': np.int32,
    'Fwd Pkts/s': np.float64,
    'Bwd Pkts/s': np.float64,
    'Pkt Len Min': np.int32,
    'Pkt Len Max': np.int64,
    'Pkt Len Mean': np.float32,
    'Pkt Len Std': np.float32,
    'Pkt Len Var': np.float32,
    'FIN Flag Cnt': np.int32,
    'SYN Flag Cnt': np.int32,
    'RST Flag Cnt': np.int32,
    'PSH Flag Cnt': np.int32,
    'ACK Flag Cnt': np.int32,
    'URG Flag Cnt': np.int32,
    'CWE Flag Count': np.int32,
    'ECE Flag Cnt': np.int32,
    'Down/Up Ratio': np.int32,
    'Pkt Size Avg': np.float64,
    'Fwd Seg Size Avg': np.float64,
    'Bwd Seg Size Avg': np.float64,
    'Fwd Byts/b Avg': np.int64,
    'Fwd Pkts/b Avg': np.int64,
    'Fwd Blk Rate Avg': np.int64,
    'Bwd Byts/b Avg': np.int64,
    'Bwd Pkts/b Avg': np.int64,
    'Bwd Blk Rate Avg': np.int64,
    'Subflow Fwd Pkts': np.int64,
    'Subflow Fwd Byts': np.int64,
    'Subflow Bwd Pkts': np.int64,
    'Subflow Bwd Byts': np.int64,
    'Init Fwd Win Byts': np.int64,
    'Init Bwd Win Byts': np.int64,
    'Fwd Act Data Pkts': np.int64,
    'Fwd Seg Size Min': np.int64,
    'Active Mean': np.float64,
    'Active Std': np.float64,
    'Active Max': np.float64,
    'Active Min': np.float64,
    'Idle Mean': np.float64,
    'Idle Std': np.float64,
    'Idle Max': np.float64,
    'Idle Min': np.float64,
    'Label': np.object,
}

pcap_dtypes = {
    'frame.time_epoch': np.float64,
    'frame.len': np.int64,
    'eth.src': np.object,
    'eth.dst': np.object,
    'ip.src': np.object,
    'ip.dst': np.object,
    'tcp.srcport': np.int16,
    'tcp.dstport': np.int16,
    'udp.srcport': np.int16,
    'udp.dstport': np.int16,
    'icmp.type': np.int8,
    'icmp.code': np.int8,
    'arp.opcode': np.int16,
    'arp.src.hw_mac': np.object,
    'arp.src.proto_ipv4': np.object,
    'arp.dst.hw_mac': np.object,
    'arp.dst.proto_ipv4': np.object,
    'ipv6.src': np.object,
    'ipv6.dst': np.object
}

best_30 = [
    # 'Timestamp',
    # 'Flow ID',
    # 'Src IP',
    # 'Dst IP',
    # 'Src Port',
    'Dst Port',
    'Protocol',
    'Flow Duration',
    'Bwd Pkt Len Max',
    'Bwd Pkt Len Min',
    'Bwd Pkt Len Mean',
    'Bwd Pkt Len Std',
    'Flow IAT Std',
    'Flow IAT Max',
    'Fwd IAT Tot',
    'Fwd IAT Max',
    'Bwd IAT Tot',
    'Bwd IAT Std',
    'Pkt Len Min',
    'Pkt Len Max',
    'Pkt Len Mean',
    'Pkt Len Std',
    'Pkt Len Var',
    'RST Flag Cnt',
    'ACK Flag Cnt',
    'ECE Flag Cnt',
    'Pkt Size Avg',
    'Bwd Seg Size Avg',
    'Init Bwd Win Byts',
    'Fwd Seg Size Min',
    'Idle Mean',
    'Idle Max',
    'Idle Min'
]

netflow_columns = [
    # 'Flow ID',
    # 'Src IP',
    # 'Src Port',
    # 'Dst IP',
    'Dst Port',
    'Protocol',
    # 'Timestamp',
    'Flow Duration',
    'Tot Fwd Pkts',
    'Tot Bwd Pkts',
    'TotLen Fwd Pkts',
    'TotLen Bwd Pkts',
    'Fwd Pkt Len Max',
    'Fwd Pkt Len Min',
    'Fwd Pkt Len Mean',
    'Fwd Pkt Len Std',
    'Bwd Pkt Len Max',
    'Bwd Pkt Len Min',
    'Bwd Pkt Len Mean',
    'Bwd Pkt Len Std',
    'Flow IAT Mean',
    'Fwd PSH Flags',
    'Flow IAT Std',
    'Flow IAT Max',
    'Flow IAT Min',
    'Bwd IAT Mean',
    'Fwd IAT Mean',
    'Fwd IAT Tot',
    'Flow Byts/s',
    'Flow Pkts/s',
    'Fwd IAT Std',
    'Fwd IAT Max',
    'Fwd IAT Min',
    'Bwd IAT Tot',
    'Bwd IAT Std',
    'Bwd IAT Max',
    'Bwd IAT Min',
    'Fwd Header Len',
    'Bwd Header Len',
    'Fwd Pkts/s',
    'Bwd Pkts/s',
    'Pkt Len Min',
    'Pkt Len Max',
    'Pkt Len Std',
    'Pkt Len Var',
    'Pkt Len Mean',
    'RST Flag Cnt',
    'FIN Flag Cnt',
    'SYN Flag Cnt',
    'PSH Flag Cnt',
    'ACK Flag Cnt',
    'URG Flag Cnt',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'CWE Flag Count',
    'ECE Flag Cnt',
    'Down/Up Ratio',
    'Pkt Size Avg',
    'Fwd Seg Size Avg',
    'Bwd Seg Size Avg',
    'Fwd Byts/b Avg',
    'Fwd Pkts/b Avg',
    'Fwd Blk Rate Avg',
    'Bwd Byts/b Avg',
    'Bwd Pkts/b Avg',
    'Bwd Blk Rate Avg',
    'Subflow Fwd Pkts',
    'Subflow Fwd Byts',
    'Subflow Bwd Pkts',
    'Subflow Bwd Byts',
    'Init Fwd Win Byts',
    'Init Bwd Win Byts',
    'Fwd Act Data Pkts',
    'Fwd Seg Size Min',
    'Active Mean',
    'Active Std',
    'Active Max',
    'Active Min',
    'Idle Mean',
    'Idle Std',
    'Idle Max',
    'Idle Min',
]

tsv_columns = [
    'frame.time_epoch',
    'frame.len',
    'eth.src',
    'eth.dst',
    'ip.src',
    'ip.dst',
    'tcp.srcport',
    'tcp.dstport',
    'udp.srcport',
    'udp.dstport',
    'icmp.type',
    'icmp.code',
    'arp.opcode',
    'arp.src.hw_mac',
    'arp.src.proto_ipv4',
    'arp.dst.hw_mac',
    'arp.dst.proto_ipv4',
    'ipv6.src',
    'ipv6.dst'
]


connection_columns = [
    # Flow / Connection
    'TimestampFirst',
    'LinkProto',
    'NetworkProto',
    'TransportProto',
    'ApplicationProto',
    # 'SrcMAC',
    # 'DstMAC',
    # 'SrcIP',
    # 'SrcPort',
    # 'DstIP',
    'DstPort',
    'Size',
    'AppPayloadSize',
    'NumPackets',
    'UID',
    'Duration',
    'TimestampLast',
    'BytesClientToServer',
    'BytesServerToClient',
    'TotalSize'
    # 'Category'
]
